services:
  - type: web
    name: cybermeme-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node server/index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
    autoDeploy: true